#ifndef ORDERBOOK_H
#define ORDERBOOK_H

#include <list>
#include <map>
#include <unordered_map>
#include <vector>

#include "Order.h"

/**
 * OrderBook implements a simplified limit order book with price-time
 * priority matching:
 *   - Orders at a better price always match first.
 *   - Among orders at the same price, the earliest order matches first.
 *
 * Internal structure:
 *   - bids_: price -> list of buy orders at that price, sorted by price
 *            descending (highest bid first is the best price for buyers).
 *   - asks_: price -> list of sell orders at that price, sorted by price
 *            ascending (lowest ask first is the best price for sellers).
 *   - Within each price level, orders are kept in a std::list, which
 *     preserves insertion order -> gives us time priority for free.
 */
class OrderBook {
public:
    // Adds a new order to the book, matching it against the opposite side
    // as much as possible. Returns any trades generated by this order.
    std::vector<Trade> addOrder(const Order& order);

    // Cancels an existing order by id. Returns true if it was found and removed.
    bool cancelOrder(int orderId);

    // Best bid / ask price. Returns -1.0 if that side of the book is empty.
    double bestBid() const;
    double bestAsk() const;

    // Total quantity resting at a given price level (0 if none).
    int depthAt(Side side, double price) const;

    // Number of resting orders currently in the book (for testing/inspection).
    size_t orderCount() const { return orderIndex_.size(); }

private:
    // price -> orders resting at that price
    std::map<double, std::list<Order>, std::greater<double>> bids_; // highest first
    std::map<double, std::list<Order>, std::less<double>> asks_;    // lowest first

    // orderId -> (side, price) so cancel() can find an order in O(1) + list erase
    struct OrderLocation {
        Side side;
        double price;
    };
    std::unordered_map<int, OrderLocation> orderIndex_;

    std::vector<Trade> matchBuyOrder(Order buyOrder);
    std::vector<Trade> matchSellOrder(Order sellOrder);

    void insertResting(const Order& order);
};

#endif // ORDERBOOK_H
